language: java
dist: xenial
jdk:
  - oraclejdk11

#addons:
#  sonarcloud:
#    organization: "alu0101109251"
#    token: ${{ secrets.SONAR_TOKEN }}
#script:
#  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

addons:
  sonarcloud:
    organization: "alu0101109251"
    token:
      secure: ${{ secrets.SONAR_TOKEN }} # encrypted value of your token
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage